version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/application/server/
    
hooks:
  BeforeInstall:
    - location: ./before_install.sh
  ApplicationStop:
    - location: ./server_stop.sh
      timeout: 300
      runas: ec2-user
  ApplicationStart:
    - location: ./server_start.sh
      timeout: 300
      runas: ec2-user