version: 0.0
os: linux
files:
  - source: /home/stocktrades/application/server/stocktrades.jar
    destination: /home/stocktrades/application/artifacts/stocktrades_old.jar
  - source: /target/stocktrades.jar
    destination: /home/stocktrades/application/server/
hooks:
  ApplicationStop:
    - location: scripts/server_stop.sh
      timeout: 300
  ApplicationStart:
    - location: scripts/server_start.sh
      timeout: 300
  ValidateService:
    - location: scripts/basic_health_check.sh