version: 0.2

phases:
  build:
    commands:
      - echo Entered the build phases
      - mvn clean package
  post_build:
    commands:
      - echo stock-trades application build successful.
       
artifacts:
    files:
      - target/stocktrades.jar
      - appspec.yml
        
    discard-paths: yes
